
/*
   Native symbol registration table for spatstat package

   Automatically generated - do not edit this file!

*/

#include "proto.h"
#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/*
   See proto.h for declarations for the native routines registered below.
*/

static const R_CMethodDef CEntries[] = {
    {"RcallK3local",      (DL_FUNC) &RcallK3local,      17},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {NULL, NULL, 0}
};

void R_init_spatstat(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
